<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/contract/smart_contract.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.SmartContractDataWrapper</code>
 */
class SmartContractDataWrapper extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.SmartContract smart_contract = 1;</code>
     */
    protected $smart_contract = null;
    /**
     * Generated from protobuf field <code>bytes runtimecode = 2;</code>
     */
    protected $runtimecode = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * @type \Protocol\SmartContract $smart_contract
     * @type string $runtimecode
     * }
     */
    public function __construct($data = NULL)
    {
        \GPBMetadata\Core\Contract\SmartContract::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract smart_contract = 1;</code>
     * @return \Protocol\SmartContract
     */
    public function getSmartContract()
    {
        return isset($this->smart_contract) ? $this->smart_contract : null;
    }

    /**
     * Generated from protobuf field <code>.protocol.SmartContract smart_contract = 1;</code>
     * @param \Protocol\SmartContract $var
     * @return $this
     */
    public function setSmartContract($var)
    {
        GPBUtil::checkMessage($var, \Protocol\SmartContract::class);
        $this->smart_contract = $var;

        return $this;
    }

    public function hasSmartContract()
    {
        return isset($this->smart_contract);
    }

    public function clearSmartContract()
    {
        unset($this->smart_contract);
    }

    /**
     * Generated from protobuf field <code>bytes runtimecode = 2;</code>
     * @return string
     */
    public function getRuntimecode()
    {
        return $this->runtimecode;
    }

    /**
     * Generated from protobuf field <code>bytes runtimecode = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRuntimecode($var)
    {
        GPBUtil::checkString($var, False);
        $this->runtimecode = $var;

        return $this;
    }

}

