<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/TronInventoryItems.proto

namespace GPBMetadata\Core;

class TronInventoryItems
{
    public static $is_initialized = false;

    public static function initOnce()
    {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true)
        {
            return;
        }
        $pool->internalAddGeneratedFile(
            '
�
core/TronInventoryItems.protoprotocol"-
InventoryItems
type (
items (BP
org.tron.protosBTronInventoryItemsZ)github.com/tronprotocol/grpc-gateway/corebproto3'
            , true);

        static::$is_initialized = true;
    }
}

